### ISSUE TITLE
No luck on io.js

### ISSUE THREAD

**Issue by binarykitchen** [mafintosh/node-gyp-install#7]
```
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 404 response downloading https://nodejs.org/dist/v2.5.0/node-v2.5.0.tar.gz
gyp ERR! stack     at Request.<anonymous> (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:251:14)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:169:7)
gyp ERR! stack     at Request.onRequestResponse (/usr/lib/node_modules/npm/node_modules/request/request.js:992:10)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:415:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:305:20)
gyp ERR! stack     at emitOne (events.js:77:13)
```

but I did this before

```
$ node-gyp-install                                                                                                                                               
node-gyp-install http request https://iojs.org/dist/v2.5.0/iojs-v2.5.0.tar.gz
node-gyp-install http 200 https://iojs.org/dist/v2.5.0/iojs-v2.5.0.tar.gz
node-gyp-install info install node-gyp should now work for v2.5.0
```

what is missing here?

**Comment by mafintosh** [comment]
this looks very weird. do you have a full reproducible example i can try?

**Comment by binarykitchen** [comment]
i think i fixed this but cannot explain why. with these commands

`sudo npm -g remove npm`

`sudo apt-get install iojs --reinstall`

somehow a bad npm version got installed and messed up with all that. guess that's an unfortunate side effect when we have npm dealing with node.js and io.js both.

looking forward to the merge of node.js and io.js, then those weird issues will be gone (hopefully!)
